---
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker --version
  - docker info

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

  # download the Galaxy Docker image and build it to test the playrole
  - mkdir $HOME/galaxy-docker
  - wget -q -O - https://github.com/bgruening/docker-galaxy-stable/archive/master.tar.gz | tar xzf - --strip-components=1 -C $HOME/galaxy-docker
  # remove the submodule role
  - rm $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/* -rf

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i "localhost," tests/syntax.yml --syntax-check
  # Copy the ansible-playbook from this repo into the Docker roles directory and build the image.
  - cp -r ./* $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - ls -l $HOME/galaxy-docker/galaxy/roles/galaxyprojectdotorg.galaxyextras/
  - cd $HOME/galaxy-docker/galaxy && docker build -t galaxy .
