# TODO: following task is kind of a crutch - shouldn't be needed.
- name: "Run common_startup.sh to create welcome.html from sample"
  shell: scripts/common_startup.sh
  environment:
    GALAXY_VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  args:
    chdir: "{{ galaxy_server_dir }}"
  become: True
  become_user: "{{ galaxy_user_name }}"

- name: Ensure galaxy_log dir exists
  file: path={{ galaxy_log_dir }} state=directory owner={{ galaxy_user_name }} group={{ galaxy_user_name }}
