- name: Create nginx upload_store dir
  file: state=directory path={{ nginx_upload_store_path }}

- name: Place configuration files
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode=0600
  with_items:
    - { src: 'htpasswd.j2',               dest: '/etc/nginx/htpasswd' }
    - { src: 'nginx_ide.conf.j2',         dest: '{{ nginx_conf_directory }}/ide.conf' }
    - { src: 'nginx_galaxy_web.conf.j2',  dest: '{{ nginx_conf_directory }}/galaxy_web.conf' }
    - { src: 'nginx_uwsgi.conf.j2',       dest: '{{ nginx_conf_directory }}/uwsgi.conf' }
    - { src: 'nginx.conf.j2',             dest: '{{ nginx_conf_path }}' }
  notify: Restart Nginx

- name: disable https via letsencrypt by default
  file: src=/dev/null dest={{ nginx_conf_directory }}/letsencrypt.conf owner=root group=root state=link

# Letsencrypt-specific configuration:

- name: Create letsencrypt configuration directory
  file: path=/etc/letsencrypt state=directory mode=0755
  when: galaxy_extras_config_letsencrypt

- name: Create letsencrypt wellknown directory
  file: path=/etc/letsencrypt/wellknown state=directory mode=0755
  when: galaxy_extras_config_letsencrypt

- name: get the letsencrypt script from github repository
  get_url:
    url: https://raw.githubusercontent.com/lukas2511/letsencrypt.sh/d81eb58536e3ae1170de3eda305688ae28d0575b/letsencrypt.sh
    dest: /usr/bin/letsencrypt.sh
    mode: "u=rwx,g=rx,o=r"
  when: galaxy_extras_config_letsencrypt

- name: Setup letsencrypt-specific configuration files
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root group=root mode={{ item.mode }}
  with_items:
    - { src: 'nginx_letsencrypt.conf.j2', dest: '{{ nginx_conf_directory }}/letsencrypt-enabled.conf', mode: "u=rw,g=r,o=r" }
    - { src: 'letsencrypt.conf.j2',       dest: '/etc/letsencrypt/letsencrypt.conf', mode: "u=rw,g=r,o=r" }
    - { src: 'letsencrypt_refresh.sh.j2', dest: '/usr/local/bin/letsencrypt_refresh', mode: "u=rwx,g=rx,o=r" }
  when: galaxy_extras_config_letsencrypt
